$schema: "config.schema.json"

appName: "Galvanico"

logLevel: debug

database:
  url: "postgresql://root@127.0.0.1:26257/defaultdb?sslmode=disable"

broker:
  url: "nats://127.0.0.1:4222"

auth:
  provider: zitadel
  settings:
    clientId: a
    domain: a

world:
  travelSpeed: 1