services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:17bec0f151cf384b9b1d19c8f8dbe8b1a301acdba56e6232051ed6e2e6b46a6d
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:3072e8ea890fe66b5921f75c1385b5f49b59a7f46171d697517d186830131fa7
    ports:
      - "4222:4222"
      - "8222:8222"
