services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:9957538cc1586355bd6c26af8198b3b1d4302e7ce3422f59b8b23d01cbd8503a
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:57f45fba83001bfff519e918035305f02eb897a172f82d43933136e0f6aceb1e
    ports:
      - "4222:4222"
      - "8222:8222"
