services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:17bec0f151cf384b9b1d19c8f8dbe8b1a301acdba56e6232051ed6e2e6b46a6d
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:75c706fc8028f61e12e4576c8c443eff5a6fb14842a291f2d0c15acc8c0fc883
    ports:
      - "4222:4222"
      - "8222:8222"
