services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:c152c330b6ac0702b509929d204c69fbea142a6c4cf2c4a2f17e9b83aa5fa769
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:57f45fba83001bfff519e918035305f02eb897a172f82d43933136e0f6aceb1e
    ports:
      - "4222:4222"
      - "8222:8222"
