services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:0a2671147906da20d81e05df39af7eea8f0d3d1e57327d4285cc513613620703
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:d80d5773c4e558914e79e2886f54a64963d1f07d8638b0c49217cf6fb8e95049
    ports:
      - "4222:4222"
      - "8222:8222"
