services:
  cockroach:
    image: cockroachdb/cockroach:latest@sha256:90463eb46726908959dceb97c2a6b555db7701bc43aa166d4990b1ad8892a9da
    ports:
      - "26257:26257"
      - "25255:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/data/cockroach:/cockroach/cockroach-data"
#    environment:
#      COCKROACH_USER: "game"
#      COCKROACH_PASSWORD: "game"

  nats:
    image: nats:latest@sha256:76fe53997736051e3511ddc26d585abd679fe3a30dbf74d19418bb0035fde031
    ports:
      - "4222:4222"
      - "8222:8222"
