name: DCO Check

on:
  pull_request:
    branches-ignore:
      - renovate/**

jobs:
  check:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@fb284c903a7673a3d4b0bdd104479a6f0d46dae7 # v1