name: DCO Check

on:
  pull_request:
    branches-ignore:
      - renovate/**

jobs:
  check:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@41ccac559c7150e0e9ffea00785fd173c473e2ee # v1