name: Integration tests - E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ./client

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./client

      - name: Build
        run: bun run build
        working-directory: ./client

      - name: Run Playwright tests
        run: bun test:e2e
        working-directory: ./client

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30