name: Go Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: go get .

      - name: Generate Mocks and Run Tests
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report@latest
          go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Test Summary
        uses: test-summary/action@77bb5a9f9c572416423f9a157cbf1159c1e75a4c # v1
        with:
          paths: report.xml