name: Go Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: go get .

      - uses: brian-pickens/go-test-report@v1
        with:
          packages: "./..."
          summary: "true"
          GO111MODULE: "auto"