name: Release Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Required for git describe --tags

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: '^1.21' # Or your desired Go version

      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Build binary for Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o ${{ github.event.repository.name }}_linux_amd64

      - name: Build binary for Darwin amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ${{ github.event.repository.name }}_darwin_amd64

      - name: Build binary for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o ${{ github.event.repository.name }}_windows_amd64.exe

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          files: |
            ${{ github.event.repository.name }}_linux_amd64
            ${{ github.event.repository.name }}_darwin_amd64
            ${{ github.event.repository.name }}_windows_amd64.exe
          generate_release_notes: true