name: Release Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0 # Required for git describe --tags

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '^1.21' # Or your desired Go version

      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Build binary for Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o ${{ github.event.repository.name }}_linux_amd64

      - name: Build binary for Darwin amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ${{ github.event.repository.name }}_darwin_amd64

      - name: Build binary for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o ${{ github.event.repository.name }}_windows_amd64.exe

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          files: |
            ${{ github.event.repository.name }}_linux_amd64
            ${{ github.event.repository.name }}_darwin_amd64
            ${{ github.event.repository.name }}_windows_amd64.exe
          generate_release_notes: true